### ISSUE TITLE
预训练好的模型文件下载不了？

### ISSUE THREAD

**Issue by amoonhappy** [bityigoss/mtl-text-recognition#1]
麻烦更新下链接，感谢！

**Comment by bityigoss** [comment]
@amoonhappy 更新了一个CRNN中文模型(单任务训练)，ResNet+BiLSTM+CTC，可以进行测试；模型还在训练中，后续还会给出其他的预训练模型。
链接:https://pan.baidu.com/s/1k6__hYRdq8BnyihP8ImLWw 提取码:iiw7 
谢谢！
