### ISSUE TITLE
用你提供的dict和权重进行预测中文都错了。。。

### ISSUE THREAD

**Issue by amoonhappy** [bityigoss/mtl-text-recognition#3]
不知道什么原因。。。

**Comment by bityigoss** [comment]
@amoonhappy 能发几个图片case给我试试吗？项目里面demo_images下的图片，部分文字字体、颜色、大小不同以及背景等原因，识别效果可能不好，但是一般的情况识别应该没什么问题，比如字幕那种的，基本都没能准确识别；

**Comment by bityigoss** [comment]
@amoonhappy 另外因为我训练多个版本的模型，如果是因为字符错位了，我稍后可以更新一个与dict对应的模型；

**Comment by bityigoss** [comment]
@amoonhappy 我更新了一个crnn预训练模型的下载链接，如果有问题你可以重新下载试试
