### ISSUE TITLE
还有一个问题

### ISSUE THREAD

**Issue by amoonhappy** [bityigoss/mtl-text-recognition#4]
我的训练数据很多有几百万图片，没法转成lmdb格式吧？这种情况怎么处理需要改哪个地方从硬盘直接读取图片数据？感谢！

**Comment by bityigoss** [comment]
@amoonhappy 可以转成lmdb，我的训练数据集900万张通过utils/create_lmdb_dataset.py可以转换为lmdb文件，然后使用现有方式读取就行。
