### ISSUE TITLE
ctc_loss function error

### ISSUE THREAD

**Issue by jackson1895** [bityigoss/mtl-text-recognition#5]
您好，非常感谢您开源您的代码，在运行您代码过程中，cost.backward()出现如下错误，RuntimeError: setStorage: sizes [64, 262, 55], strides [20174, 77, 2], and storage offset 0 requiring a storage size of 1291168 are out of bounds for storage with numel 1291136

这个错误您遇到了吗？ 请问这个怎么解决，谢谢！

**Comment by bityigoss** [comment]
@jackson1895 你好，我这边训练时没有遇到你的那个问题，请问你是在train.py报错还是mtl_train.py报错？以及你的模型运行参数/日志是什么样的？
我的torch版本是1.1.0；
