### ISSUE TITLE
训练中loss下降缓慢

### ISSUE THREAD

**Issue by xiaomei1995** [bityigoss/mtl-text-recognition#7]
我现在使用resnet768_bilstm384_ctc，数据集大概700W，字库7000左右，batch_size为64，使用Adadelta，从开始到现在已经47W次迭代了，loss为1.09，差不多5000次才下降0.001，准确率不到50%，这是有什么问题吗？您平时训练大概多久就能完成呢？

**Comment by bityigoss** [comment]
@xiaomei1995 我的训练日志，你可以参考一下；batch_size=224，一般几万次迭代之后就能得到一个较靠谱的结果了
[resnet768_bilstm384_ctc.log](https://github.com/bityigoss/mtl-text-recognition/files/3655881/resnet768_bilstm384_ctc.log)
建议你检查你的数据，如验证数据的字符分布与训练数据的字符分布情况，数据集的复杂程度等；

如果你发现问题，欢迎push request，共享训练数据或者训练数据生成方法。
